language: go

go:
  - 1.10
  - 1.11
  - tip

env:
  - PATH=$PATH:$GOPATH/bin
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -t ./...
script:
  - $GOPATH/bin/goveralls -service=travis-ci
